import { PointerLockControls } from 'three/examples/jsm/controls/PointerLockControls';
export declare class Mouse {
    private _x;
    private _y;
    private _movementX;
    private _movementY;
    private _isMoving;
    private _mouseStopTimer;
    private _isLeftButtonDown;
    private _isLeftButtonPressed;
    private _isLeftButtonUp;
    private _isRightButtonDown;
    private _isRightButtonPressed;
    private _isRightButtonUp;
    private _isMidButtonDown;
    private _isMidButtonPressed;
    private _isMidButtonUp;
    private _wheelY;
    private _wheelX;
    private _enabled;
    private _pointerLock;
    readonly pointerLock: PointerLockControls;
    readonly x: number;
    readonly y: number;
    readonly movementX: number;
    readonly movementY: number;
    readonly isMoving: boolean;
    readonly isLeftButtonDown: boolean;
    readonly isLeftButtonPressed: boolean;
    readonly isLeftButtonUp: boolean;
    readonly isRightButtonDown: boolean;
    readonly isRightButtonPressed: boolean;
    readonly isRightButtonUp: boolean;
    readonly isMidButtonDown: boolean;
    readonly isMidButtonPressed: boolean;
    readonly isMidButtonUp: boolean;
    readonly wheelY: number;
    readonly wheelX: number;
    enabled: boolean;
    init(): void;
    lock(): void;
    private unlockFunction;
    unlock(): void;
    private onMouseMove;
    private onMouseDown;
    private onMouseUp;
    private onWheelMove;
}
